version: 2
sources:
  - name: bq_ny_taxi
    database: nyc-taxi-data-pipeline-250123
    schema: nyc_taxi_trips
    tables:
      - name: temp_fhv_trips
      - name: temp_green_taxi
      - name: temp_yellow_taxi